/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihandb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Fitriyah
 */
public class TampilanGUI extends javax.swing.JFrame {

    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    ArrayList<ProgramStudi> dataProdi;

    private void kosongkan_form() {
        jTextFieldkode.setEditable(true);
        jTextFieldkode.setText(null);
        jTextFieldnamaprodi.setText(null);
        jTextFieldjenjang.setText(null);
        jTextFieldnamakaprodi.setText(null);
    }

    private int masukkanData(Connection conn, String kodeProdi, String namaProdi, String jenjang, String namaKaprodi) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("INSERT INTO program_studi (kode_prodi,nama_prodi,jenjang,nama_kaprodi) VALUES(?,?,?,?)");
        pst.setString(1, kodeProdi);
        pst.setString(2, namaProdi);
        pst.setString(3, jenjang);
        pst.setString(4, namaKaprodi);
        return pst.executeUpdate();
    }

    private int updateData(Connection conn, String kodeProdi, String namaProdi, String jenjang, String namaKaprodi) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("UPDATE program_studi SET nama_prodi=?, jenjang=?, nama_kaprodi=? WHERE kode_prodi=?");
        pst.setString(1, namaProdi);
        pst.setString(2, jenjang);
        pst.setString(3, namaKaprodi);
        pst.setString(4, kodeProdi);
        return pst.executeUpdate();
    }

    private int deleteData(Connection conn, String kodeProdi) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("DELETE FROM program_studi WHERE kode_prodi=?");
        pst.setString(1, kodeProdi);
        return pst.executeUpdate();
    }

    private void tampil(Connection conn) {
        dataProdi.clear();
        try {
            String sql = "select * from program_studi";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                ProgramStudi data = new ProgramStudi();
                data.setKodeProdi(String.valueOf(rs.getObject(1)));
                data.setNamaProdi(String.valueOf(rs.getObject(2)));
                data.setJenjang(String.valueOf(rs.getObject(3)));
                data.setNamaKaprodi(String.valueOf(rs.getObject(4)));
                dataProdi.add(data);
            }
            DefaultTableModel model = (DefaultTableModel) jTableProdi.getModel();
            model.setRowCount(0);
            for (ProgramStudi data : dataProdi) {

                Object[] baris = new Object[4];
                baris[0] = data.getKodeProdi();
                baris[1] = data.getNamaProdi();
                baris[2] = data.getJenjang();
                baris[3] = data.getNamaKaprodi();
                model.addRow(baris);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form TampilanGUI
     */
    public TampilanGUI() {

        try {
            dataProdi = new ArrayList<>();
            initComponents();
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/TugasPBO", "postgres", "pipit1702");
            tampil(conn);
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldkode = new javax.swing.JTextField();
        jTextFieldnamaprodi = new javax.swing.JTextField();
        jTextFieldjenjang = new javax.swing.JTextField();
        jTextFieldnamakaprodi = new javax.swing.JTextField();
        jScrollPaneprodi = new javax.swing.JScrollPane();
        jTableProdi = new javax.swing.JTable();
        jButtonsimpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonCetak = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("KODE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 87, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("PRODI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("JENJANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 167, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("KAPRODI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 207, -1, -1));
        getContentPane().add(jTextFieldkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 84, 185, -1));
        getContentPane().add(jTextFieldnamaprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 124, 185, -1));
        getContentPane().add(jTextFieldjenjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 164, 185, -1));
        getContentPane().add(jTextFieldnamakaprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 204, 185, -1));

        jTableProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE", "PRODI", "JENJANG", "KAPRODI"
            }
        ));
        jTableProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdiMouseClicked(evt);
            }
        });
        jScrollPaneprodi.setViewportView(jTableProdi);

        getContentPane().add(jScrollPaneprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 84, 420, 347));

        jButtonsimpan.setText("SIMPAN");
        jButtonsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 378, -1, -1));

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 378, -1, -1));

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 378, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("DATA PROGRAM STUDI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButtonCetak.setText("CETAK");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 407, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihandb/unnamed.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsimpanActionPerformed
        // TODO add your handling code here:
        String kodeProdi = jTextFieldkode.getText().trim();
        String namaProdi = jTextFieldnamaprodi.getText();
        String jenjang = jTextFieldjenjang.getText();
        String namaKaprodi = jTextFieldnamakaprodi.getText();
        if (!kodeProdi.isEmpty() && !namaProdi.isEmpty() && !jenjang.isEmpty() && !namaKaprodi.isEmpty()) {

            try {
                // TODO add your handling code here:
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/TugasPBO", "postgres", "pipit1702");
                int k = masukkanData(conn, kodeProdi, namaProdi, jenjang, namaKaprodi);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Simpan Berhasil");
                } else {
                    this.peringatan("Simpan Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Mahasiswa Gagal");
        }
        jTextFieldkode.setText("");
        jTextFieldnamaprodi.setText("");
        jTextFieldjenjang.setText("");
        jTextFieldnamakaprodi.setText("");
        kosongkan_form();
    }//GEN-LAST:event_jButtonsimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String kodeProdi = jTextFieldkode.getText().trim();
        String namaProdi = jTextFieldnamaprodi.getText();
        String jenjang = jTextFieldjenjang.getText();
        String namaKaprodi = jTextFieldnamakaprodi.getText();

        if (!kodeProdi.isEmpty() && !namaProdi.isEmpty() && !jenjang.isEmpty() && !namaKaprodi.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/TugasPBO", "postgres", "pipit1702");
                int k = updateData(conn, kodeProdi, namaProdi, jenjang, namaKaprodi);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Update Berhasil");
                } else {
                    this.peringatan("Update Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Mahasiswa Gagal");
        }

        jTextFieldkode.setText("");
        jTextFieldnamaprodi.setText("");
        jTextFieldjenjang.setText("");
        jTextFieldnamakaprodi.setText("");
        kosongkan_form();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String kodeProdi = jTextFieldkode.getText().trim();

        if (!kodeProdi.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/TugasPBO", "postgres", "pipit1702");
                int k = deleteData(conn, kodeProdi);
                if (k > 0) {
                    tampil(conn);
                    peringatan("Delete Berhasil");
                } else {
                    peringatan("Delete Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            peringatan("Kode Prodi tidak boleh kosong");
        }

        jTextFieldkode.setText("");
        kosongkan_form();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdiMouseClicked
        // TODO add your handling code here:
        int baris = jTableProdi.rowAtPoint(evt.getPoint());
        String kodeProdi = jTableProdi.getValueAt(baris, 0).toString();
        jTextFieldkode.setText(kodeProdi);

        String namaProdi = jTableProdi.getValueAt(baris, 1).toString();
        jTextFieldnamaprodi.setText(namaProdi);

        String jenjang = jTableProdi.getValueAt(baris, 2).toString();
        jTextFieldjenjang.setText(jenjang);

        String namaKaprodi = jTableProdi.getValueAt(baris, 3).toString();
        jTextFieldnamakaprodi.setText(namaKaprodi);
    }//GEN-LAST:event_jTableProdiMouseClicked

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/TugasPBO", "postgres", "pipit1702");

            //File jasperFile = new File("src/pbopertemuan6/mahasiswa.jasper");
            // JasperPrint jp = JasperFillManager.fillReport(jasperFile.getPath(), null, conn);
            String jrxmlFile = new String("src/latihandb/reportProdi.jrxml");

            JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPaneprodi;
    private javax.swing.JTable jTableProdi;
    private javax.swing.JTextField jTextFieldjenjang;
    private javax.swing.JTextField jTextFieldkode;
    private javax.swing.JTextField jTextFieldnamakaprodi;
    private javax.swing.JTextField jTextFieldnamaprodi;
    // End of variables declaration//GEN-END:variables
}
